---
title: 'You Want to Know: Cases, Variables, and Study Goals'
categories: activities
date: '2019-06-04'
output:
  html_document:
    df_print: paged
  pdf_document: default
slug: activity-you-want-to-know
tags:
- tidy-data
- unit-of-observarion
- variables
banner: img/banners/banner-question-mark.jpeg
---

\pagestyle{empty}

**Instructions.**  In each scenario below, 

* determine what variables you would need to collect and whether each is categorical or quantitative, 

* describe or sketch a graph you would make to give you an initial impression
regarding the answer to the question of interest,

* determine the paramater(s) of interest and explain how they are different
from the variables, 

<!-- * and state the null and alternative hypotheses if you are going to -->
<!-- do a hypothesis test, -->

* determine whether you are using a paired design.

Sometimes there may be more than one way to design the study, but don't 
design a poor study when a better option is available.

1. You want to know what proportion of students at your institution got a flu shot this year.

1. You want to know whether male students or female students were more likely to get a flu shot this year.

1. You want to know whether people who got a flu shot were more likely or less likely to get the flu.

1. You want to know which of two vaccines is better at preventing flu.

1. You want to know whether a new drug works better than an old drug at reducing cholesterol.

1. You want to know whether rhubarb grows faster or slower if you cover it with a bucket for 3 weeks.

1. You want to know whether people can swim faster if they wear wetsuits.

You might find it handy to organize you work into a table like this:

Scenario | Variables (type) | Parameter(s)  | Plot           | Paired?
-------- | ---------------- | ------------- | -------------- | -------------
1        | vaccinated (yes/no) -- categorical | proportion of all students who were vaccinated | bar chart showing number of vaccinated/unvaccinated students | no
2 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
3 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
4 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
5 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
6 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
7 | | |  <BR><BR><BR><BR> \vspace*{0.25in}
