---
title: "Pre-workshop questions"
date: "2019-05-30"
description: "Responses to the pre-conference questions"
---


###. What do you teach students about handling data? (That is, not about the analysis of data but about how data is stored, accessed, transformed?)

- Not taught
- I have demonstrated using Statcrunch and Excel, but not as much data handling as I should.
- This is not a topic I formally cover.
- I don’t.
- I have had the students import data from Excel spreadsheets into R, as well as importing from text files associated with our textbook (Investigating Statistical Concepts, Applications, and Methods  by Rossman and Chance). Apart from that, we cover a little how to subset data, but that is about it. It's not that I don't understand the importance of having the students do this, it's just that I'm not sure myself (as a mathematician learning how to teach statistics) how to handle data well. I'm hoping to learn more from the workshop.
- I do a little bit of work with Excel in class – we use the Lock textbook, with StatKey software, so it works best to store and manipulate data in Excel.
- We teach nothing about this.



> In our newly reformed course, unfortunately this is still not “a thing” coursewide. Coursewide, in most sections, data “handling” is likely non-existent except for downloading spreadsheets of data from the Lock5 site and then uploading it into StatKey.
>
> In my own sections, students have two projects, one very minor, one considerably bigger that requires some “data handling.”   In the first, they use a data set of about 150 real cases from the student survey we give out to about 600 students. Students answer it through a google form, but then my students get a subset of those cases - 150 - in spreadsheet form, where I cleaned up the column headings, putting codebook info in separate sheet. Students still have to “clean” the data for two variables and then make a data display (with StatKey) of the variables and make some commentary. The “cleaning” is the important part. They have to describe what decisions they made. If they don’t clean the data, they notice problems trying to get a graph.
>
> In the bigger project at end of semester, where studnets go through the investigative cycle, the data handling part requires students to load data they collected on 3 subjects each into a shared google sheet.  They download that sheet as excel  to ultimately do their own analysis. Depending on what question they are answering, they may need to create new columns (like differences between other columns or some other manipulation of columns already there). That data prep allows them to bring the spreadsheet into StatKey as csv file to do the analyses.

### Which topics do you find unsatisfying? (This could be because you just don’t like them, because students don’t succeed in mastering the topic, or because they make no sense/don’t fit in.)

- Chi-Squared.  We don’t have time to really dive into the topic.
- I do not enjoy teaching probability.  I personally enjoy it, but my students do not, and they do not see the connection to the rest of the course.
- My students struggle with binomial probabilities because they have trouble seeing the purpose.
- Advanced statistical testing that doesn’t connect to anything for them...
- Adding math fails and multiple interpretations of data... 
- I can't say I'm unsatisfied by anything. I've generally enjoyed Rossman and Chance's treatment.
- Type I and Type II errors. Covering inference for multiple parameters (one mean, one proportion, …); by the end, students are pretty sick of it. (I do try to show them how it all fits together, so each new situation isn’t something new they need to learn.)
- Regression, because we give it such short shrift, it becomes just an annoying little exercise.

>  Our newly revised course uses Lock curriculum, so nothing is terribly unsatisfying.  Maybe some of the descriptive stats that we rush through, but students don’t really understand well (despite them being middle school concepts and skills). I wish we had more time for things like data handling. We’re also struggling to find the right expectation for students to know how different randomization tests are done…. And now I’m struggling to think through how to deal with ASAs recommendation to lose the idea of statistical significance and rejection/no rejection decision…very glad you addressed it; I had literally read some of the special issue just last week!


### Which lesson have you been aching to improve?

- The entire beginning of my course.  Introducing data collection and summary.
- Central Limit Theorem
- Either improve the way I teach binomial probabilities because they struggle with it or two sample hypothesis testing because we have just added the topic to the curriculum.
- Interactive lessons need to greatly increase. Adding some notice and wonder, especially with least squares but along the way so they will notice and wonder by then.
- Type I/II errors, connection between CI and HT
- Adding real data so they can actually see the relevance.

> Every semester  I make improvements to almost every lesson in terms of trying to decrease lecture time in each class, to devote  more time to group activities and/or  student work time (through guided applets or the like). I’m constantly revising activities or choosing different ones. 


### Hypothetical: Suppose you were tasked to develop a version of your statistics course that is only 2/3 as long as your current course. Which topics would you drop or consolidate? (Don’t worry, you won’t be asked to do this. We merely want to prompt you to prioritize the topics in your course.)

- Chi-Squared and Linear Regression
- The entire beginning of my course.  Introducing data collection and summary.
- We revamped the old course a year ago and indeed, did  just that  - dropped all probability theory, use of  t,z tables, etc
- I would probably not formally cover the basics mean median mode bar graphspie charts and would consider streamlining probability.
- Predicting intervals about mean responses with least squares regression.
- This is a difficult question for me to answer. Being a mathematician by training, I find that it is taking time for me to develop a sense for what statisticians would perceive as the most important topics in an introductory course. I'm hoping that by participating in professional development programs such as StatPREP will help with this.
- Nothing else to drop now – already dropped probability, Binomial dist, much about Normal dist, chi-square.
- Drop probability and the details of binomial distribution


### What data sets do you currently use that you would like to give a higher profile?

- We use the data sets provided in textbooks.
- Student created data...
- I have primarily been using data sets that are supplied by our textbook authors. It would be great to learn how to import "real, live" data sets for my students to use.
- None


### Are there data sets that you’d like to incorporate but haven’t had a chance to do so?

- Not sure what is out there.  I need to know where to find them.
- I am looking forward to using the suggested data sets provided by the StatPREP website.
- Always looking for a good data set. I find it hard to find. Often, the codebook is missing so you can’t make sense of the data or the codebook not detailed enough. I tried Kaggle this year - no good.

