---
title: "The standard deviation and the 95% summary interval"
date: "2019-04-19"
weight: 6
description: "Relating the 95% summary interval to a traditional measure of spread: the standard deviation"
output:
  word_document:
    reference_docx: lesson-style.docx
categories:
  - activities
tags:
  - "summary interval"
banner: "img/banners/missing.png"
---


```{r include = FALSE}
library(SDSdata)
library(knitr)
library(LittleApp)
library(DT)
center_app <- get_app_info("spread")
```

`r SDSdata::word_pdf_links()`

# Orientation 

The length of the *95% summary interval* is a pretty good way to describe the amount of variation in a variable. Yet statisticians tend to prefer using the *standard deviation*. This makes sense, since statisticians are interested in confusing the poor student by using obscure names ("Deviation?". Really?) and formulas that can be hard to understand. ... Not really!! Even though the standard deviation has an odd name and seems complicated, the actual reason it's used so much by statisticians is that it has some nice mathematical properties.

The purpose of this lesson is to help you understand the standard deviation in terms of the 95% summary interval. Often, there's a very close and relatively simple relationship between the two. This means that it's possible to make sense of the standard deviation without formulas. (There's still the odd name, but there's nothing we can do about that!)
 
# Activity

Open up the [Center and spread](`r center_app$url`) Little App (see footnote^[<`r center_app$url`>])., and select the `Births_2014` data frame. Set the sample size to n = 200.

1. Set the response variable to be `baby_wt`, the weight of the baby at birth. You'll see that there is variability, that is, not every baby weighs exactly the same.

2. Turn on the display of the mean and the standard deviation. Look closely at the annotation for the standard deviation. The standard deviation is a kind of measuring unit, like the inch marks on a ruler. The annotation is being drawn as a ruler. The mean is exactly in the middle and there are tick marks at ± 1 standard deviation and at ± 2 standard deviations.^[Sometimes the ± 2 marks don't fit within the frame, so those aren't included on the ruler.]

4. The numerical value of the standard deviation is the length between tick marks, just as an inch is the length between marks on a ruler. 

    * Use the measuring stick to find the numerical value for the standard deviation for the data shown in your plot.
    * Open the "Statistics" tab underneath the graphic where you will find printed the standard deviation as calculated directly from the data. Compare that number to the number you found in (a). They should be just about the same.
    * Use the measuring stick to find the length of the whole ruler being displayed. Compare that to the number you read in (b) from the Statistics tab. 
    
    `r question_blank("*Describing how long the ruler is by how many standard deviations it is long.*", breaks = 1)`
    
5. Turn on the display of the 95% summary interval. See where the ends of the 95% summary interval fall along the standard deviation ruler.

    `r question_blank("*How long is the standard deviation compared to the length of the 95% summary interval?*", breaks = 2)`
    
    * Make the sample size bigger, say, n = 2000. 
    
    `r question_blank("*Does the relationship between the 95% summary interval and the standard deviation change?*", breaks = 1)`
    
    `r question_blank("*Fill in the blank in the following statement.* (Feel free to round to a whole number.)", breaks = 0)`  
    
    > The 95% summary interval is ____ times as long as the standard deviation. 
    
6. The simple relationship between the 95% summary interval and the standard deviation often holds, but not always. Some variables consistently have the standard deviation ruler mis-aligned with the 95% summary interval.

    * Set the response variable to be APGAR score. Try several New Samples. 
    
    `r question_blank("*Does the 95% summary interval align with the ruler?*", breaks = 1)`
    
  
    * Turn on the violin density display. 
    
    `r question_blank("*Is the density shape symmetric (top to bottom)? Does it have a very long tail?*", breaks = 2)`
    
    * Go back to `baby_wt` and look at the violin. 
    
    `r question_blank("*How does the shape of this violin differ from that for APGAR. Is it symmetric? Does it have a very long tail?*", breaks = 3)`
    
    `r question_blank("*For response variables with a bell-shaped distribution, roughly how long is the 95% summary interval in terms of the standard deviation? Circle one of the following.*", breaks = 0)`
    
    > The 95% summary interval is         the same lengthas         twice as long as         three times longer than        the standard deviation.
    
    `r question_blank("*For response variables that don't have a bell-shaped distribution, e.g. they have a long tail on one side but not the other, does the answer you gave to the previous question still hold?", breaks = 1)`


    

----------------------

Version 0.1, `r Sys.Date()`, Daniel Kaplan, 
