---
title: "Joining MAA Connect"
date: "2019-06-06"
tags: 
  - "MAA connect"
banner: "/img/banners/MAA-logo.png"
summary: "Signing up StatPREP Hub Community on MAA Connect"
---


We are excited to invite you to join the StatPREP Hub Communities online group using [MAA Connect](http://connect.maa.org/)! 


Below, you will find instructions on logging into MAA Connect if you are a MAA member, or registering for a guest account if you are not. You will also find general set-up instructions, as well as information on accessing the different communities you want to join. We encourage you to read/listen along to these instructions as you are getting logged in for the first time. There may be specific information you wish to change before making a post, such as your profile picture, your email preferences, and your discussion signature: 


* MAA Connect: [Getting Started (video)](https://www.youtube.com/watch?v=Pgt4cf-eB3c)

* MAA Connect: [Getting Started (PDF)](https://drive.google.com/file/d/1Cy67ziOwS4D5XpZDiGmPsP0su6Yf6Ny0/view)


Once you have created your profile and logged in, head over to the [StatPREP Hub Communities](https://connect.maa.org/communities/community-home?CommunityKey=6be8da59-c237-4569-bc85-b4ab59cbaf91) group and click “Join”. You can find this group by clicking on the tab that says “Communities > All Communities”. You may also want to join the StatPREP Grant Community for future updates and resources. 