---
title: "Tips for Creating an Active Classroom"
author: "R Pruim"
date: "6/7/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
slug: activity-tips
categories: 
    - activity-guide
tags:
    - teaching-tips
banner: img/banners/missing.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Have a **goal**.

    It is easier to design an activity if you have a clear idea what
    you want the activity to acheive.
    
    One way to come up with goals is to think about things that have 
    given your students trouble in the past. These are the places 
    where you can have the biggest impact.

2. Have an **assessment plan**.

    How will you tell if your students have acheived your goal? Having an 
    assessment plan can focus your ideas for the activity. It will also 
    give you information to tell whether your goals have been acheived.

3. Enumerate student **pre-requisites**.

    Learning is about getting from point 
    A (what the students already know/can do)
    to point B (what you want them to know/be able to do).
    Knowing the particular things you plan to build on will
    help you design your activity.
    
    If you are uncertain that the pre-requisites are in place, 
    you can build in a portion of the activity to diagnose this.
    
    Is there anything students must do in advance to prepare?

4. **Design** the activity.

    Sometimes the key idea presents itself without much effort.
    
    Textbook examples can provide inspiration for activities.
    
    Brainstorm with colleagues.

5. **Iterate.**

    Take some time to consider how well the activity worked.
    What worked well? How might it be improved?
    What questions did the students ask while they were working?
    Were the instructions clear?
    Did anything surprise you?
    Are there elements (ideas, data sets, tasks, instructions, etc.)
    of this activity that can be recycled?
   
6. **Borrow** and **share**.

    Collaborate with colleagues.
    
    Find ways to make your best activities public.