---
title: "Little Apps: Orientation"
description: "What's in a Little App?"
author: "Danny Kaplan"
weight: -100
categories: ["Little App"]
date: "2019-04-16"
banner: "img/compass.jpg"
---

```{r include = FALSE}
library(LittleApp)
library(knitr)
```

*Little Apps* provide interactive computing with no coding to calculate statistics, fit models, and display statistical concepts.

Every Little App is built around a common framework:

* At the core is a data graphic. The vertical axis is the response variable and the horizontal axis is the explanatory variable. 
* Controls enable you to select a data set and variables. 
* Set the sample size and easily display a new sample.
* Statistics are shown as annotations, always with respect to the data.
* A statistics tab, under the graph, gives numerical descriptions of the statistics.
* Most have measurement "sticks" that allow you easily to read values and differences from the graphic.

Each Little App is a specialist in a particular style of display or statistical annotation, e.g. proportions, regression, t-tests, etc.

Enjoy! You can learn a lot just playing with data.

