---
title: "Tips for an active classroom"
description: "Some ideas for engaging students in discussion about statistics." 
output: 
  html_document:
    theme: readable
---

Many instructors believe that learning is enhanced in a classroom where students  are active participants rather than the passive recipients of a lecture. This document describes some general techniques for fostering an active classroom  that can be used in a wide range of lesson topics. (There are also tips for specific topics included in the instructor guide for each topic.)

What's key is to constantly look for opportunities to *force* students to make a choice, offer a suggestion, or state an interpretation or an opinion. 
Common kindness or politeness often causes us to wait for a volunteer. But  being kind or polite is only incidental to your purpose. Waiting for a volunteer causes problems, e.g. the same small group of people answer all the time or you end up answering your own question in order to avoid deadly silence. What's primary is to get all  students engaged. You can be forceful in a gentle way. 

# Ask early and often

Make it clear to students that you want *interesting* answers. Whether the answer offered is right or not is of secondary importance, because even a wrong answer invites consideration of what's wrong with it or how you can decide that the answer is reasonable or that the answer is right or wrong.

**Ask many simple, short questions**. It's good to ask easy questions and expect students to give easy answers. Do this over and over again throughout the semester to reinforce situations where the answer should become instantaneous and automatic. Here are some examples. We provide answers even though those will be obvious to you. We do this to indicate to you, the instructor, how short and simple the answers can be. 

- What's the confidence level that's conventional? (Ans: 95%)
- What is this fitted line called? (A regression line.)
- What's the square of the standard deviation called? (the variance)
- Which is smaller, the standard deviation or the standard error of the mean? (the standard error)
- What's the symbol for the correlation coefficient? 
- There are two main kinds of variables. What are they called? (quantitative and categorical)
- What do we call this kind of plot? (Depends on what plot you are showing them.)
    
It can be good, after an answer has been given by one student, to say to the class, "OK.  I want to  hear this from everyone. Shout it out. What's the [your question here]?" Not enough people responded. "No, I want to hear from *everyone*."
    
[EXERCISE FOR WORKSHOP: Write down three simple questions whose answers should become automatic. Perhaps assign each person a topic from their course.]

It's also good, of course, to **ask questions that require some careful consideration, thought, and judgement**. If no answer is forthcoming, just stand there and wait. Count to thirty before intervening. Often, someone will throw out an answer (right or wrong) just to end the silence. This gives you something to work with. Ask the class (or individuals in the class) whether they think the answer is right or wrong. If they  aren't sure, ask them what they would look for to decide, or what's confusing them about the question and proposed answer.

The fear is that nobody will give any answer. If this happens, you have some options:

- Give me a reasonable answer even if it's wrong. Follow up if necessary by asking what the *form* of a reasonable answer would be. 
- Ask for them to give a wrong answer. Then they should explain why they thought that the answer they gave was wrong.
- The instructor poses a answer, very possibly a wrong answer, then asks the students whether the answer was right or wrong.
- Select a student at random. Ask them for an answer, but allow them to ask their own question of the class to help them frame or decide on an answer. Or ask them what they would need to know to start to put together an answer. Or ask them to give an answer that's reasonable but that could well be wrong -- then ask the class to evaluate that answer. Was it right or wrong? How do you know?
        
Another possible unfortunate outcome is that the answer comes from the small group of students who are always answering. This disengages the other students in the class. Rather than trying to shut down the people who are always answering, ask the class, "Somebody else. Tell me if that answer is right or wrong?" or "How would you know if that answer is right."

**Don't forget the obvious**. We're often so wrapped up in thinking about challenging questions or decisions that we forget to say what's obvious. Is there a pattern shown by a graph that is being displayed to the class. Ask  a student to *describe the basic pattern* simply, e.g. cars generally drive faster than trucks, or "there's considerable overlap" or "the groups are distinct" or "there's a positive relationship", and so on.
    
# Ask students to take a stand.

Some examples: 

* The choice of a distribution shape
* The position of a value. 
* A yes/no question (e.g. is the median greater than the mean)
* Causation. Does A cause B, or B cause A, or do they have a common cause.
* Even, did I write that formula right? Or, I calculated this value.  Is it  right?

* Making the choice
    - Individuals: 
        - Make a choice or say that they can't decide.
        - Force them to make a choice.
    - Groups: come to a consensus or announce a hung jury.
* Displaying the choice. You want this to happen fast, to avoid dead time in the classroom while a roster is being passed around.
    - Raise their hand
    - Knock on the table
    - Hold up a card
    - Use a clicker system
* Resolving disagreement. 
    - Get enthusiastic representatives of each choice to come to the front of the room. Have them explain their position to the class.
    - After the set of explanations, for each possible choice ask students who prefer that choice to raise their hand. Then raise the other hand if it was the enthusiast's explanation that caused them to change from a previous c choice.

# Ask students to contribute a solution or possibility or opinion.

- Common and uncommon values of a variable.
- Interesting explanatory variables.
- Interesting covariates.
- Find a "better" result than the instructor.

# Ask students to give an explanation or translate a result into everyday terms. 

Options: 

- Pick a student to do so in front of the class.

    Then, ask the class to say whether they  like or don't like the answer. If they don't  like it, how would they improve it? If they do like it, what is it that they like about it?

- Have all students/groups write down their translation. Pass them up to the front  and read selected ones, both good and bad. 

    Instructor quickly scans through for good and bad answers. Start with some bad answers (or, an answer that exemplifies a misconception). Ask the class for a quick show of what they think. Allow volunteers to explain and/or the instructor explains what's the misconception involved. 

# Combine student results.

Many activities have students calculate or eyeball a value.

* Students have calculated a value. You start  with a "low"  value.  Ask students to tap on the table if their value is bigger than the low value. Then gradually increase the value. Some students will stop tapping. Keep increasing the value until the tapping stops. That tells you what the "highest" value is. 
     - Perhaps sketch a graph showing the loudness of the tapping versus the value. Start at a nominal value of 1 and gradually decrease to 0. You can have a student do this. 
         - Translate the graph into a probability distribution. (The negative of the derivative of the curve.) You might want to do  this yourself or train  students to do it.  
     - Why have students all tap at the beginning? (1) It wakes them up. (2) They are forced to engage from the very beginning. (3) A student who isn't tapping at the beginning is fair game to be asked, "What is your value?" That might help elicit misconceptions or other problems of understanding.
     - Before starting, elicit from students what the lowest possible value is  and what the highest possible value is.  
    - Example: Find the distribution  of ages of the students in the class. Start at zero,  jump to  15, then slowly up  one year at a time.

* Students write result on a Post-It. Stick them to the board to make a distribution, e.g. a histogram- or dot-plot like  configuration.

# Don't forget the data!

One of the greatest opportunities to create student engagement comes from the setting and applicability of the data. Describe the data set you are using and the meaning of important variables. Encourage students to look for interesting explanatory variables, or to choose a response variable that is of meaning to them. 

To illustrate, consider the data from the National Health and  Nutrition Evaluation Survey (NHANES) that is one of the set available throughout the Little App series. Some examples of opportunities for engagement ...

- Have students do a web search on NHANES to understand what it is.
- Review some of the variables included in the `NHANES` data frame. You can do this *within* the Little App by going to the "codebook" tab in the app. 
Before starting the lessons, make sure the students understand what the  "unit of observation" is (an individual person surveyed as part of the NHANES project) and any variables that will be used: 
    - `HomeOwn` - whether the person owns or rents the home they live in. (Possible questions: Across the US,  what fraction  of households own their home?)
    - `Poverty` - the *income* of the person's family, stated as a multiple of the government's official poverty level. (Possible questions to ask students: What is the current "poverty level?" How poor would a family be that is at the poverty level? At twice the poverty level? For what government services is the poverty level used as a eligibility qualification?)

You might decide to use other data, but the same principles apply of understanding how the data are organized and what the variables stand for. 




-------------

Authors:  Danny Kaplan & ...

Version 0.5 `r  Sys.Date()`